"""
Problem 2
https://projecteuler.net/problem=2

Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,…

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def main():
	MAX_VALUE = 4_000_000
	sum_even_terms = 0
	
	gen = fibonacci_generator()
	_, n = next(gen), next(gen)
	
	while n < MAX_VALUE:
		n = next(gen)
		if n % 2 == 0:
			sum_even_terms += n
			
	print(sum_even_terms)

def fibonacci_generator():
	a, b = 0, 1
	while True:
		yield a
		a, b = b, a + b

if __name__ == "__main__":
    main()
