"""
Problem 12
https://projecteuler.net/problem=12

Highly Divisible Triangular Number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 =28. The first ten terms would be:
1,3,6,10,15,21,28,36,45,55,…

Let us list the factors of the first seven triangle numbers:
𝟏:1
𝟑:1,3
𝟔:1,2,3,6
𝟏𝟎:1,2,5,10
𝟏𝟓:1,3,5,15
𝟐𝟏:1,3,7,21
𝟐𝟖:1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
from math import sqrt

def main():
    MAX_DIVISORS = 500
    
    for n in range(1, 100_000_000):
        tri_num = sum([i for i in range(1, n)])
        d = divisors(tri_num)
        if len(d) > MAX_DIVISORS:
            break
                    
    print(tri_num)
    
def divisors(n: int):
    d = list()
    ceil = int(sqrt(n)) + 1
    
    for i in range(1, ceil):
        if n % i == 0:
            d.append(i)
            
            if i != n // i:
                d.append(n // i)
                
    return d

if __name__ == "__main__":
    main()
