"""
Problem 44
https://projecteuler.net/problem=44

Pentagon Numbers
Pentagonal numbers are generated by the formula, P(n) = n(3n - 1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P(4) + P(7) = 22 + 70 = P(8). However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and difference are pentagonal and D = |P(j) - P(k)| is minimised; what is the value of D?
"""
from itertools import combinations
from pprint import pprint

def main():
    min_d = 1_000_000_000
    pentagonal_numbers = set([(n * (3 * n - 1)) // 2 for n in range(1, 5000)])
    # print(pentagonal_numbers)

    c = combinations(pentagonal_numbers, 2)

    for p in c:
        if (p[0] + p[1]) in pentagonal_numbers:
            if abs(p[0] - p[1]) in pentagonal_numbers:
                # print(*p)
                if abs(p[0] - p[1]) < min_d:
                    min_d = abs(p[0] - p[1])

    print(min_d)


if __name__ == "__main__":
    main()
