"""
Problem 45
https://projecteuler.net/problem=45

Triangular, Pentagonal, and Hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle: T(n) = n(n + 1)/2; 1, 3, 6, 10, 15, ...
Pentagonal: P(n) = n(3n - 1)/2: 1, 5, 12, 22, 35, ...
Hexagonal: H(n) = n(2n - 1): 1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from pprint import pprint

def main():
    result = 0

    t = set([(n * (n + 1)) // 2 for n in range(1, 1_000_000)])
    p = set([(n * (3 * n - 1)) // 2 for n in range(1, 1_000_000)])
    h = set([(n * (2 * n - 1)) for n in range(1, 1_000_000)])
    # print(pentagonal_numbers)

    for _t in t:
        if _t <= 40755:
            continue

        if _t in p and _t in h:
            result = _t
            break

    print(result)


if __name__ == "__main__":
    main()
